# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -c++ -r -o /home/jordan/dev/octra/build/octraR/src/octra_wrap.cpp /home/jordan/dev/octra/build/octraR/src/octrar.i


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = SWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  delayedAssign(defName,  .values, assign.env = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################



setClass('C++Reference', contains = 'ExternalReference')
setClass('_p_Circle', contains = 'C++Reference')



setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

suppressMessages(suppressWarnings(setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})))

# Start of Circle_m_radius_set

`Circle_m_radius_set` = function(self, s_m_radius)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  
  ;.Call('R_swig_Circle_m_radius_set', self, s_m_radius, PACKAGE='octrar');
  
}

attr(`Circle_m_radius_set`, 'returnType') = 'void'
attr(`Circle_m_radius_set`, "inputTypes") = c('_p_Circle', 'numeric')
class(`Circle_m_radius_set`) = c("SWIGFunction", class('Circle_m_radius_set'))

# Start of Circle_m_radius_get

`Circle_m_radius_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_Circle_m_radius_get', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`Circle_m_radius_get`, 'returnType') = 'numeric'
attr(`Circle_m_radius_get`, "inputTypes") = c('_p_Circle')
class(`Circle_m_radius_get`) = c("SWIGFunction", class('Circle_m_radius_get'))

# Start of new_Circle

`Circle` = function(radius)
{
  ;ans = .Call('R_swig_new_Circle', radius, PACKAGE='octrar');
  ans <- if (is.null(ans)) ans
  else new("_p_Circle", ref=ans);
  
  reg.finalizer(ans@ref, delete_Circle);
  ans
  
}

attr(`Circle`, 'returnType') = '_p_Circle'
attr(`Circle`, "inputTypes") = c('numeric')
class(`Circle`) = c("SWIGFunction", class('Circle'))

# Start of Circle_area

`Circle_area` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_Circle_area', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`Circle_area`, 'returnType') = 'numeric'
attr(`Circle_area`, "inputTypes") = c('_p_Circle')
class(`Circle_area`) = c("SWIGFunction", class('Circle_area'))

# Start of Circle_perimeter

`Circle_perimeter` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_Circle_perimeter', self, as.logical(.copy), PACKAGE='octrar');
  
}

attr(`Circle_perimeter`, 'returnType') = 'numeric'
attr(`Circle_perimeter`, "inputTypes") = c('_p_Circle')
class(`Circle_perimeter`) = c("SWIGFunction", class('Circle_perimeter'))

# Start of delete_Circle

`delete_Circle` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref"); 
  ;.Call('R_swig_delete_Circle', self, PACKAGE='octrar');
  
}

attr(`delete_Circle`, 'returnType') = 'void'
attr(`delete_Circle`, "inputTypes") = c('_p_Circle')
class(`delete_Circle`) = c("SWIGFunction", class('delete_Circle'))

# Start of accessor method for Circle
setMethod('$', '_p_Circle', function(x, name)

{
  accessorFuns = list('m_radius' = Circle_m_radius_get, 'area' = Circle_area, 'perimeter' = Circle_perimeter);
  vaccessors = c('m_radius');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for Circle
# Start of accessor method for Circle
setMethod('$<-', '_p_Circle', function(x, name, value)

{
  accessorFuns = list('m_radius' = Circle_m_radius_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_Circle', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('m_radius' = Circle_m_radius_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for Circle
setMethod('delete', '_p_Circle', function(obj) {delete_Circle(obj)})


